### ISSUE TITLE
As a User I want to Edit my profile

### ISSUE THREAD

**Issue by JacobLBaum** [agiledev-students-fall2022/final-project-team-resow#63]
## Estimation of work
- TBD

## Acceptance criteria
- [x] Have edit profile page be accessible from user profile
- [x] Be able to upload/replace profile picture
- [x] Be able to change your name
- [x] Be able to change your contact information
- [ ] Be able to change your password

**Comment by tasnimahmed11** [comment]
Reopened it because it is a user story
